version: "1"

services:
  go-auth:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    # command: tail -F anything
    ports:
      - "8000:8000"
  db:
    image: postgres:9.6
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
volumes:
  postgres-db:
